# -*- coding: utf-8 -*-
"""6ex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWZx9gil48dGkSItq9HlHieNixgPfhP4
"""

import requests

response = requests.get('https://www.py4e.com/code3/mbox.txt', timeout=10)
response.raise_for_status()
mbox = response.text
all_lines = mbox.split('\n')
print(f"Успешно загружено {len(all_lines)} строк")

email_counts = {}

for line in all_lines:
    if line.startswith('From '):
        if '@' in line:
            parts = line.split()
            if len(parts) >= 2:
                email = parts[1]
                if '@' in email and '.' in email:
                    email_counts[email] = email_counts.get(email, 0) + 1

if email_counts:
    max_email = ""
    max_count = 0

    for email, count in email_counts.items():
        if count > max_count:
            max_count = count
            max_email = email

    print(f"Найдено уникальных отправителей: {len(email_counts)}")
    print(f"Самый активный отправитель: {max_email}")
    print(f"Количество его писем: {max_count}")

else:
    print("Письма не найдены в файле")